//! SQLite storage via sqlx. Every query is checked against the schema at
//! compile time (`.sqlx/` holds the offline data for builds without a database).

use std::str::FromStr;

use anyhow::Context;
use diffd_core::model::{
    ActivityItem, ActivityKind, Anchor, Author, ChatMessage, Message, MessageId, Millis, ReviewId,
    ReviewMeta, ReviewStatus, Revision, Snapshot, Thread, ThreadId, ThreadKind,
};
use serde::{Deserialize, Serialize};
use sqlx::SqlitePool;
use sqlx::sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions};

/// How a review was asked for; kept so it can be rebuilt the same way.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct ReviewSpec {
    pub merge_base: Option<bool>,
    pub paths: Vec<String>,
    pub collapse: Vec<CollapseRule>,
    pub watch: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
pub struct CollapseRule {
    /// Glob matched against the file path, e.g. `web/src/gen/**` or `**/*.lock`.
    pub glob: String,
    /// Shown on the file's header, e.g. "generated by ts-rs".
    pub reason: String,
}

/// A user message the agent hasn't received yet.
#[derive(Debug, Clone, PartialEq)]
pub struct Pending {
    pub thread_id: Option<ThreadId>,
    pub message: Message,
}

#[derive(Clone)]
pub struct Store {
    pool: SqlitePool,
}

fn json<T: Serialize>(v: &T) -> String {
    serde_json::to_string(v).expect("serializing a model type cannot fail")
}

fn parse<T: for<'de> Deserialize<'de>>(s: &str) -> anyhow::Result<T> {
    serde_json::from_str(s).with_context(|| format!("corrupt JSON in database: {s}"))
}

fn author(s: &str) -> Author {
    if s == "agent" { Author::Agent } else { Author::User }
}

fn author_str(a: Author) -> &'static str {
    match a {
        Author::User => "user",
        Author::Agent => "agent",
    }
}

impl Store {
    /// Open (creating if needed) the database at `url`, e.g. `sqlite://…/diffd.db`
    /// or `sqlite::memory:`, and run migrations.
    pub async fn open(url: &str) -> anyhow::Result<Self> {
        let opts = SqliteConnectOptions::from_str(url)?
            .create_if_missing(true)
            .journal_mode(SqliteJournalMode::Wal)
            .foreign_keys(true);
        // An in-memory database exists per connection, so keep exactly one.
        let max = if url.contains(":memory:") { 1 } else { 8 };
        let pool = SqlitePoolOptions::new().max_connections(max).connect_with(opts).await?;
        sqlx::migrate!("./migrations").run(&pool).await?;
        Ok(Self { pool })
    }

    pub async fn insert_review(&self, meta: &ReviewMeta, spec: &ReviewSpec) -> anyhow::Result<()> {
        let (id, spec, rev) = (&meta.id.0, json(spec), meta.revision as i64);
        let (created, updated) = (meta.created_at as i64, meta.updated_at as i64);
        let status = "open";
        sqlx::query!(
            "INSERT INTO reviews (id, title, summary, repo_path, repo_name, from_rev, to_rev, spec, revision, status, created_at, updated_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            id, meta.title, meta.summary, meta.repo_path, meta.repo_name, meta.from, meta.to, spec, rev, status, created, updated
        )
        .execute(&self.pool)
        .await?;
        Ok(())
    }

    pub async fn set_revision(&self, id: &ReviewId, revision: Revision, at: Millis) -> anyhow::Result<()> {
        let (rev, at) = (revision as i64, at as i64);
        sqlx::query!("UPDATE reviews SET revision = ?, updated_at = ? WHERE id = ?", rev, at, id.0)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    pub async fn touch_review(&self, id: &ReviewId, at: Millis) -> anyhow::Result<()> {
        let at = at as i64;
        sqlx::query!("UPDATE reviews SET updated_at = ? WHERE id = ?", at, id.0).execute(&self.pool).await?;
        Ok(())
    }

    pub async fn review(&self, id: &ReviewId) -> anyhow::Result<Option<(ReviewMeta, ReviewSpec)>> {
        let row = sqlx::query!(
            "SELECT id, title, summary, repo_path, repo_name, from_rev, to_rev, spec, revision, status, created_at, updated_at
             FROM reviews WHERE id = ?",
            id.0
        )
        .fetch_optional(&self.pool)
        .await?;
        row.map(|r| {
            let meta = ReviewMeta {
                id: ReviewId(r.id),
                title: r.title,
                summary: r.summary,
                repo_path: r.repo_path,
                repo_name: r.repo_name,
                from: r.from_rev,
                to: r.to_rev,
                revision: r.revision as Revision,
                status: if r.status == "closed" { ReviewStatus::Closed } else { ReviewStatus::Open },
                created_at: r.created_at as Millis,
                updated_at: r.updated_at as Millis,
            };
            Ok((meta, parse(&r.spec)?))
        })
        .transpose()
    }

    /// Reviews, most recently active first, with their unread activity counts.
    pub async fn recent(&self, limit: i64) -> anyhow::Result<Vec<(ReviewMeta, u32)>> {
        let ids = sqlx::query!("SELECT id FROM reviews ORDER BY updated_at DESC LIMIT ?", limit)
            .fetch_all(&self.pool)
            .await?;
        let mut out = Vec::with_capacity(ids.len());
        for row in ids {
            let id = ReviewId(row.id);
            if let Some((meta, _)) = self.review(&id).await? {
                let unread = self.unread(&id).await?;
                out.push((meta, unread));
            }
        }
        Ok(out)
    }

    pub async fn delete_review(&self, id: &ReviewId) -> anyhow::Result<()> {
        sqlx::query!("DELETE FROM reviews WHERE id = ?", id.0).execute(&self.pool).await?;
        Ok(())
    }

    pub async fn insert_revision(&self, id: &ReviewId, snapshot: &Snapshot, at: Millis) -> anyhow::Result<()> {
        let blob = zstd::encode_all(serde_json::to_vec(snapshot)?.as_slice(), 3)?;
        let (rev, at) = (snapshot.revision as i64, at as i64);
        sqlx::query!(
            "INSERT INTO revisions (review_id, number, snapshot, created_at) VALUES (?, ?, ?, ?)",
            id.0, rev, blob, at
        )
        .execute(&self.pool)
        .await?;
        Ok(())
    }

    pub async fn latest_snapshot(&self, id: &ReviewId) -> anyhow::Result<Option<Snapshot>> {
        let row = sqlx::query!(
            "SELECT snapshot FROM revisions WHERE review_id = ? ORDER BY number DESC LIMIT 1",
            id.0
        )
        .fetch_optional(&self.pool)
        .await?;
        row.map(|r| Ok(serde_json::from_slice(&zstd::decode_all(r.snapshot.as_slice())?)?)).transpose()
    }

    pub async fn insert_thread(&self, review: &ReviewId, t: &Thread) -> anyhow::Result<()> {
        let (kind, anchor, created) = (json(&t.kind), json(&t.anchor), t.created_at as i64);
        let changed = t.changed_in.map(i64::from);
        sqlx::query!(
            "INSERT INTO threads (id, review_id, kind, anchor, resolved, changed_in, outdated, created_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            t.id.0, review.0, kind, anchor, t.resolved, changed, t.outdated, created
        )
        .execute(&self.pool)
        .await?;
        for m in &t.messages {
            self.insert_message(review, Some(&t.id), m).await?;
        }
        Ok(())
    }

    /// Save a thread's mutable state (not its messages).
    pub async fn update_thread(&self, t: &Thread) -> anyhow::Result<()> {
        let anchor = json(&t.anchor);
        let changed = t.changed_in.map(i64::from);
        sqlx::query!(
            "UPDATE threads SET anchor = ?, resolved = ?, changed_in = ?, outdated = ? WHERE id = ?",
            anchor, t.resolved, changed, t.outdated, t.id.0
        )
        .execute(&self.pool)
        .await?;
        Ok(())
    }

    pub async fn threads(&self, review: &ReviewId) -> anyhow::Result<Vec<Thread>> {
        let rows = sqlx::query!(
            "SELECT id, kind, anchor, resolved AS \"resolved: bool\", changed_in, outdated AS \"outdated: bool\", created_at FROM threads
             WHERE review_id = ? ORDER BY created_at, id",
            review.0
        )
        .fetch_all(&self.pool)
        .await?;
        let mut threads = Vec::with_capacity(rows.len());
        for r in rows {
            let id = ThreadId(r.id);
            let messages = self.messages(&id).await?;
            threads.push(Thread {
                kind: parse::<ThreadKind>(&r.kind)?,
                anchor: parse::<Anchor>(&r.anchor)?,
                resolved: r.resolved,
                changed_in: r.changed_in.map(|c| c as Revision),
                outdated: r.outdated,
                created_at: r.created_at as Millis,
                messages,
                id,
            });
        }
        Ok(threads)
    }

    /// A thread and the review it belongs to.
    pub async fn thread(&self, id: &ThreadId) -> anyhow::Result<Option<(ReviewId, Thread)>> {
        let row = sqlx::query!("SELECT review_id FROM threads WHERE id = ?", id.0)
            .fetch_optional(&self.pool)
            .await?;
        let Some(row) = row else { return Ok(None) };
        let review = ReviewId(row.review_id);
        let thread = self.threads(&review).await?.into_iter().find(|t| &t.id == id);
        Ok(thread.map(|t| (review, t)))
    }

    async fn messages(&self, thread: &ThreadId) -> anyhow::Result<Vec<Message>> {
        let rows = sqlx::query!(
            "SELECT id, author, body, created_at, delivered_at FROM messages WHERE thread_id = ? ORDER BY created_at, id",
            thread.0
        )
        .fetch_all(&self.pool)
        .await?;
        Ok(rows
            .into_iter()
            .map(|r| Message {
                id: MessageId(r.id),
                author: author(&r.author),
                body: r.body,
                created_at: r.created_at as Millis,
                delivered_at: r.delivered_at.map(|d| d as Millis),
            })
            .collect())
    }

    pub async fn insert_message(&self, review: &ReviewId, thread: Option<&ThreadId>, m: &Message) -> anyhow::Result<()> {
        let thread = thread.map(|t| t.0.as_str());
        let (author, created, delivered) = (author_str(m.author), m.created_at as i64, m.delivered_at.map(|d| d as i64));
        sqlx::query!(
            "INSERT INTO messages (id, review_id, thread_id, author, body, created_at, delivered_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
            m.id.0, review.0, thread, author, m.body, created, delivered
        )
        .execute(&self.pool)
        .await?;
        Ok(())
    }

    pub async fn chat(&self, review: &ReviewId) -> anyhow::Result<Vec<ChatMessage>> {
        let rows = sqlx::query!(
            "SELECT id, author, body, created_at, delivered_at FROM messages
             WHERE review_id = ? AND thread_id IS NULL ORDER BY created_at, id",
            review.0
        )
        .fetch_all(&self.pool)
        .await?;
        Ok(rows
            .into_iter()
            .map(|r| ChatMessage {
                id: MessageId(r.id),
                author: author(&r.author),
                body: r.body,
                created_at: r.created_at as Millis,
                delivered_at: r.delivered_at.map(|d| d as Millis),
            })
            .collect())
    }

    /// User messages the agent hasn't received, oldest first.
    pub async fn undelivered(&self, review: &ReviewId) -> anyhow::Result<Vec<Pending>> {
        let rows = sqlx::query!(
            "SELECT id, thread_id, body, created_at FROM messages
             WHERE review_id = ? AND author = 'user' AND delivered_at IS NULL ORDER BY created_at, id",
            review.0
        )
        .fetch_all(&self.pool)
        .await?;
        Ok(rows
            .into_iter()
            .map(|r| Pending {
                thread_id: r.thread_id.map(ThreadId),
                message: Message {
                    id: MessageId(r.id),
                    author: Author::User,
                    body: r.body,
                    created_at: r.created_at as Millis,
                    delivered_at: None,
                },
            })
            .collect())
    }

    pub async fn mark_delivered(&self, ids: &[MessageId], at: Millis) -> anyhow::Result<()> {
        let at = at as i64;
        for id in ids {
            sqlx::query!("UPDATE messages SET delivered_at = ? WHERE id = ?", at, id.0).execute(&self.pool).await?;
        }
        Ok(())
    }

    pub async fn add_activity(&self, review: &ReviewId, at: Millis, kind: ActivityKind) -> anyhow::Result<ActivityItem> {
        let (at_i, kind_json) = (at as i64, json(&kind));
        let seq = sqlx::query!("INSERT INTO activity (review_id, at, kind) VALUES (?, ?, ?) RETURNING seq AS \"seq!: i64\"", review.0, at_i, kind_json)
            .fetch_one(&self.pool)
            .await?
            .seq;
        Ok(ActivityItem { seq: seq as u64, at, kind })
    }

    pub async fn activity(&self, review: &ReviewId) -> anyhow::Result<Vec<ActivityItem>> {
        let rows = sqlx::query!("SELECT seq AS \"seq!: i64\", at, kind FROM activity WHERE review_id = ? ORDER BY seq", review.0)
            .fetch_all(&self.pool)
            .await?;
        rows.into_iter()
            .map(|r| Ok(ActivityItem { seq: r.seq as u64, at: r.at as Millis, kind: parse(&r.kind)? }))
            .collect()
    }

    pub async fn read_seq(&self, review: &ReviewId) -> anyhow::Result<u64> {
        let row = sqlx::query!("SELECT seq FROM read_marks WHERE review_id = ?", review.0).fetch_optional(&self.pool).await?;
        Ok(row.map_or(0, |r| r.seq as u64))
    }

    pub async fn set_read_seq(&self, review: &ReviewId, seq: u64) -> anyhow::Result<()> {
        let seq = seq as i64;
        sqlx::query!(
            "INSERT INTO read_marks (review_id, seq) VALUES (?, ?)
             ON CONFLICT (review_id) DO UPDATE SET seq = MAX(seq, excluded.seq)",
            review.0, seq
        )
        .execute(&self.pool)
        .await?;
        Ok(())
    }

    async fn unread(&self, review: &ReviewId) -> anyhow::Result<u32> {
        let read = self.read_seq(review).await? as i64;
        let rows = sqlx::query!("SELECT kind FROM activity WHERE review_id = ? AND seq > ?", review.0, read)
            .fetch_all(&self.pool)
            .await?;
        let mut n = 0;
        for r in rows {
            if parse::<ActivityKind>(&r.kind)?.from_agent() {
                n += 1;
            }
        }
        Ok(n)
    }
}
