// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelWakeData, CancelWakeResponses, ContextFileData, ContextFileErrors, ContextFileResponses, DeleteReviewData, DeleteReviewErrors, DeleteReviewResponses, HighlightData, HighlightResponses, ListReviewsData, ListReviewsResponses, RangeData, RangeErrors, RangeResponses, RepoFilesData, RepoFilesErrors, RepoFilesResponses, ReviewStateData, ReviewStateErrors, ReviewStateResponses, WakeData, WakeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Highlight fenced code from a message with the same grammars and classes as the diff.
 */
export const highlight = <ThrowOnError extends boolean = false>(options: Options<HighlightData, ThrowOnError>): RequestResult<HighlightResponses, unknown, ThrowOnError> => (options.client ?? client).post<HighlightResponses, unknown, ThrowOnError>({
    url: '/api/highlight',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listReviews = <ThrowOnError extends boolean = false>(options?: Options<ListReviewsData, ThrowOnError>): RequestResult<ListReviewsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListReviewsResponses, unknown, ThrowOnError>({ url: '/api/reviews', ...options });

/**
 * Delete a review, its threads and its history.
 */
export const deleteReview = <ThrowOnError extends boolean = false>(options: Options<DeleteReviewData, ThrowOnError>): RequestResult<DeleteReviewResponses, DeleteReviewErrors, ThrowOnError> => (options.client ?? client).delete<DeleteReviewResponses, DeleteReviewErrors, ThrowOnError>({ url: '/api/reviews/{id}', ...options });

/**
 * Everything the page needs to show a review.
 */
export const reviewState = <ThrowOnError extends boolean = false>(options: Options<ReviewStateData, ThrowOnError>): RequestResult<ReviewStateResponses, ReviewStateErrors, ThrowOnError> => (options.client ?? client).get<ReviewStateResponses, ReviewStateErrors, ThrowOnError>({ url: '/api/reviews/{id}', ...options });

/**
 * One file outside the diff, highlighted.
 */
export const contextFile = <ThrowOnError extends boolean = false>(options: Options<ContextFileData, ThrowOnError>): RequestResult<ContextFileResponses, ContextFileErrors, ThrowOnError> => (options.client ?? client).get<ContextFileResponses, ContextFileErrors, ThrowOnError>({ url: '/api/reviews/{id}/context', ...options });

/**
 * Every file in the review's repository, for browsing beyond the diff.
 */
export const repoFiles = <ThrowOnError extends boolean = false>(options: Options<RepoFilesData, ThrowOnError>): RequestResult<RepoFilesResponses, RepoFilesErrors, ThrowOnError> => (options.client ?? client).get<RepoFilesResponses, RepoFilesErrors, ThrowOnError>({ url: '/api/reviews/{id}/files', ...options });

/**
 * The diff between two points in a review's history.
 */
export const range = <ThrowOnError extends boolean = false>(options: Options<RangeData, ThrowOnError>): RequestResult<RangeResponses, RangeErrors, ThrowOnError> => (options.client ?? client).get<RangeResponses, RangeErrors, ThrowOnError>({ url: '/api/reviews/{id}/range', ...options });

/**
 * Stop waiting for this waiter (its session ended).
 */
export const cancelWake = <ThrowOnError extends boolean = false>(options: Options<CancelWakeData, ThrowOnError>): RequestResult<CancelWakeResponses, unknown, ThrowOnError> => (options.client ?? client).delete<CancelWakeResponses, unknown, ThrowOnError>({ url: '/api/wake', ...options });

/**
 * Long-poll until the user leaves feedback an agent here should hear about
 * (200, with the notice), or the wait ends (204). Used by `diffd hook`.
 */
export const wake = <ThrowOnError extends boolean = false>(options: Options<WakeData, ThrowOnError>): RequestResult<WakeResponses, unknown, ThrowOnError> => (options.client ?? client).get<WakeResponses, unknown, ThrowOnError>({ url: '/api/wake', ...options });
