// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * One entry in the page's activity feed.
 */
export type ActivityItem = {
    seq: number;
    at: U64;
    kind: ActivityKind;
};

export type ActivityKind = {
    notes: number;
    collapsed: number;
    type: 'opened';
} | {
    threadId: ThreadId;
    path: string;
    line: number;
    type: 'userCommented';
} | {
    threadId: ThreadId;
    path: string;
    line: number;
    type: 'agentReplied';
} | {
    threadId: ThreadId;
    path: string;
    line: number;
    type: 'agentNoted';
} | {
    revision: U32;
    paths: Array<string>;
    type: 'revision';
} | {
    messageId: MessageId;
    type: 'agentSaid';
} | {
    request: ShowRequest;
    type: 'show';
};

/**
 * Where a thread lives: a line range on one side of a file.
 */
export type Anchor = {
    path: string;
    side: Side;
    start: number;
    end: number;
    /**
     * The exact anchored text, used to follow the lines across revisions.
     */
    text: string;
    range: CommitRange | null;
};

export type Author = 'user' | 'agent';

/**
 * What the server embeds in each page it serves; the page renders from it.
 */
export type Boot = {
    reviews: Array<ReviewSummary>;
    page: 'home';
} | {
    state: ReviewState;
    page: 'review';
} | {
    message: string;
    page: 'notFound';
};

export type ClientMsg = {
    threadId: ThreadId;
    messageId: MessageId;
    anchor: Anchor;
    body: string;
    type: 'comment';
} | {
    threadId: ThreadId;
    messageId: MessageId;
    body: string;
    type: 'reply';
} | {
    threadId: ThreadId;
    resolved: boolean;
    type: 'resolve';
} | {
    drafting: boolean;
    type: 'drafting';
} | {
    messageId: MessageId;
    body: string;
    type: 'chat';
} | {
    seq: number;
    type: 'read';
} | {
    requestId: number;
    query: CodeQuery;
    path: string;
    line: number;
    col: number;
    type: 'code';
};

export type CodeAnswer = {
    locations: Array<CodeLocation>;
    type: 'locations';
} | {
    markdown: string;
    type: 'hover';
} | {
    reason: string;
    type: 'unavailable';
};

/**
 * Where a language server points: a file in the repository (a relative
 * path), or outside it (an absolute path, e.g. a library's source).
 */
export type CodeLocation = {
    path: string;
    external: boolean;
    /**
     * 1-based.
     */
    line: number;
    col: number;
};

/**
 * What the page can ask a language server about a position.
 */
export type CodeQuery = 'definition' | 'typeDefinition' | 'hover' | 'references';

/**
 * A commit between the review's two sides.
 */
export type Commit = {
    sha: string;
    short: string;
    subject: string;
    author: string;
    time: U64;
};

/**
 * Two points in a review's history: commits, or the working tree for `to: null`.
 */
export type CommitRange = {
    from: string;
    to: string | null;
};

/**
 * A language server's error or warning on the new side of a file.
 * Lines are 1-based; columns count UTF-16 code units from 0, as in the page.
 */
export type Diagnostic = {
    line: number;
    col: number;
    endLine: number;
    endCol: number;
    severity: Severity;
    message: string;
    /**
     * The tool that reported it, e.g. `rustc`, `pyright`.
     */
    source: string | null;
};

/**
 * One file's diff: both sides in full, aligned line by line.
 */
export type FileDiff = {
    path: string;
    oldPath: string | null;
    status: FileStatus;
    /**
     * Display name of the language, when we recognise it.
     */
    language: string | null;
    omitted: Omitted | null;
    /**
     * Changes the rows can't show: the file mode, line endings, the final
     * newline, a submodule's commit. Short phrases, e.g. "mode 100644 → 100755".
     */
    details: Array<string>;
    /**
     * Why the file starts collapsed (set by the agent, e.g. "generated by ts-rs").
     */
    collapsed: string | null;
    /**
     * What kind of file it is, as diffd can tell by itself: `test`, `generated`.
     */
    labels: Array<string>;
    added: number;
    removed: number;
    old: SideText | null;
    new: SideText | null;
    /**
     * The whole file, aligned: (old line index, new line index), 0-based.
     */
    rows: Array<Row>;
    /**
     * New-side lines (1-based) that changed since the previous revision.
     */
    since: Array<number>;
};

export type FileStatus = 'added' | 'deleted' | 'modified' | 'renamed' | 'unchanged';

/**
 * A chapter of the agent's guided tour: files that change together for one
 * reason, read one after another.
 */
export type Group = {
    /**
     * What these changes are, in a few words, e.g. "The rate limiter API" or "Database migrations".
     */
    title: string;
    /**
     * One or two plain sentences on what changed here and why, shown above the chapter's code.
     */
    summary: string | null;
    /**
     * Files in the diff, as paths, directories or globs (`web/src**`, `*.sql`), in reading order.
     */
    files: Array<string>;
};

/**
 * The commits a review spans, oldest first along first parents, so the page
 * can walk them one at a time or diff any two.
 */
export type History = {
    /**
     * The commit the review compares against.
     */
    base: string;
    commits: Array<Commit>;
    /**
     * The review ends at the working tree, so uncommitted changes follow the last commit.
     */
    worktree: boolean;
    /**
     * Only the newest commits are listed.
     */
    truncated: boolean;
};

/**
 * A label on some files (e.g. `frontend`), which the user can hide.
 */
export type Label = {
    /**
     * Short and lowercase, e.g. `frontend`, `backend`, `docs`, `generated`, `test`.
     */
    name: string;
    /**
     * Paths, directories or globs, e.g. `web**` or `*.sqlx`.
     */
    files: Array<string>;
};

/**
 * How the agent arranged the review for reading: who it is, related changes
 * grouped together, and labels the user can hide files by.
 */
export type Layout = {
    /**
     * The agent's name as its harness gives it, e.g. "Claude" or "Codex".
     */
    agent: string | null;
    groups: Array<Group>;
    labels: Array<Label>;
};

/**
 * [`ReviewState`] without the snapshot: what a page that already has the
 * current revision needs when its socket (re)connects. A big review's
 * snapshot is megabytes, and the page already holds it.
 */
export type LiveState = {
    review: ReviewMeta;
    threads: Array<Thread>;
    regions: Array<Region>;
    layout: Layout;
    history: History;
    chat: Array<Message>;
    activity: Array<ActivityItem>;
    presence: Presence;
    readSeq: number;
    diagnostics: {
        [key: string]: Array<Diagnostic>;
    };
};

/**
 * A message in a thread, or in the chat.
 */
export type Message = {
    id: MessageId;
    author: Author;
    /**
     * Markdown.
     */
    body: string;
    createdAt: U64;
    deliveredAt: U64 | null;
};

/**
 * One message in a thread or in the chat.
 */
export type MessageId = string;

export type NoteKind = 'explain' | 'why' | 'risk' | 'question';

/**
 * Why a file's contents aren't shown.
 */
export type Omitted = 'binary' | 'tooLarge' | 'submodule';

/**
 * What the agent is doing, as far as the page can tell.
 */
export type Presence = 'listening' | 'working' | 'away';

/**
 * A range the agent labelled when sharing: tests, or code folded behind a summary.
 */
export type Region = {
    path: string;
    side: Side;
    /**
     * 1-based inclusive line range; `None` means the whole file.
     */
    lines: [
        number,
        number
    ] | null;
    kind: RegionKind;
    /**
     * For folds: what changed in there, in plain language.
     */
    summary: string | null;
    /**
     * The anchored text, used to follow the lines across revisions.
     */
    text: string;
};

export type RegionKind = 'test' | 'fold';

/**
 * A review: one shared diff and its conversation.
 */
export type ReviewId = string;

export type ReviewMeta = {
    id: ReviewId;
    title: string;
    summary: string | null;
    repoPath: string;
    repoName: string;
    from: string;
    /**
     * `None` means the working tree.
     */
    to: string | null;
    revision: U32;
    status: ReviewStatus;
    createdAt: U64;
    updatedAt: U64;
};

/**
 * Everything the page needs to render a review. It's embedded in the HTML so
 * the page works offline, and sent again when the socket (re)connects from a
 * page without the current revision (otherwise it gets [`LiveState`]).
 */
export type ReviewState = {
    review: ReviewMeta;
    snapshot: Snapshot;
    threads: Array<Thread>;
    /**
     * Tests and folds the agent marked.
     */
    regions: Array<Region>;
    /**
     * Who the agent is, and how it grouped and labelled the files.
     */
    layout: Layout;
    /**
     * The commits in the review's range.
     */
    history: History;
    chat: Array<Message>;
    activity: Array<ActivityItem>;
    presence: Presence;
    /**
     * Activity up to this sequence number has been seen by the user.
     */
    readSeq: number;
    /**
     * Language servers' diagnostics, by path (files in the diff and open for context).
     */
    diagnostics: {
        [key: string]: Array<Diagnostic>;
    };
};

export type ReviewStatus = 'open' | 'closed';

/**
 * A review in the recent list on the home page.
 */
export type ReviewSummary = {
    review: ReviewMeta;
    /**
     * Agent activity the user hasn't seen.
     */
    unread: number;
};

/**
 * An aligned pair of 0-based line indices; `None` where one side has no line.
 */
export type Row = [
    number | null,
    number | null
];

export type ServerMsg = {
    state: ReviewState;
    type: 'state';
} | {
    state: LiveState;
    type: 'resume';
} | {
    review: ReviewMeta;
    delta: SnapshotDelta;
    type: 'revision';
} | {
    regions: Array<Region>;
    type: 'regions';
} | {
    layout: Layout;
    type: 'layout';
} | {
    thread: Thread;
    type: 'thread';
} | {
    message: Message;
    type: 'chat';
} | {
    item: ActivityItem;
    type: 'activity';
} | {
    presence: Presence;
    type: 'presence';
} | {
    path: string;
    diagnostics: Array<Diagnostic>;
    type: 'diagnostics';
} | {
    requestId: number;
    answer: CodeAnswer;
    type: 'code';
} | {
    history: History;
    type: 'history';
} | {
    request: ShowRequest;
    type: 'show';
} | {
    id: MessageId;
    type: 'ack';
} | {
    message: string;
    type: 'error';
} | {
    message: string;
    type: 'gone';
};

/**
 * How bad a language server's diagnostic is.
 */
export type Severity = 'error' | 'warning' | 'info' | 'hint';

export type ShowRequest = {
    path: string;
    side: Side;
    start: number;
    end: number;
    message: string;
};

export type Side = 'old' | 'new';

/**
 * One side of a file.
 */
export type SideText = {
    lines: Array<string>;
    /**
     * Per line, flattened `[start, end, class, start, end, class, …]`.
     * `class` indexes [`SyntaxClass::ALL`].
     */
    syntax: Array<Array<number>>;
    /**
     * Per line, flattened `[start, end, …]`: tokens difftastic marks as novel.
     */
    novel: Array<Array<number>>;
};

/**
 * Everything the page needs to render one revision of a review.
 */
export type Snapshot = {
    revision: U32;
    files: Array<FileDiff>;
    symbols: Array<Symbol>;
};

/**
 * A revision as changes to the one before it. An agent editing one file of
 * a big review would otherwise resend every file (megabytes) on each save.
 */
export type SnapshotDelta = {
    /**
     * The revision this applies to.
     */
    base: U32;
    revision: U32;
    /**
     * Every file's path, in the new order. Paths not in `files` are the
     * base's files, unchanged; base files missing here are gone.
     */
    paths: Array<string>;
    /**
     * Files that are new or differ in any way from the base's.
     */
    files: Array<FileDiff>;
    /**
     * The definitions in `files`, with `file` indexing the new order.
     */
    symbols: Array<Symbol>;
};

/**
 * A definition found by the tags queries: what `gd` jumps to.
 */
export type Symbol = {
    name: string;
    /**
     * e.g. "function", "class", "method", "module".
     */
    kind: string;
    /**
     * Index into [`Snapshot::files`].
     */
    file: number;
    side: Side;
    line: number;
    start: number;
    end: number;
    /**
     * The whole definition's first and last line (1-based), e.g. a function with its body.
     */
    lines: [
        number,
        number
    ];
};

export type Thread = {
    id: ThreadId;
    kind: ThreadKind;
    anchor: Anchor;
    resolved: boolean;
    changedIn: U32 | null;
    /**
     * The anchored code can no longer be found.
     */
    outdated: boolean;
    messages: Array<Message>;
    createdAt: U64;
};

/**
 * A thread of messages anchored to lines, or an agent note.
 */
export type ThreadId = string;

export type ThreadKind = {
    type: 'comment';
} | {
    kind: NoteKind;
    order: number;
    type: 'note';
};

/**
 * What woke the agent, and what to tell it.
 */
export type WakeNotice = {
    /**
     * Addressed to the agent: what happened and what to do.
     */
    message: string;
    reviews: Array<WakeReview>;
};

export type WakeReview = {
    review_id: string;
    title: string;
    url: string;
    comments: number;
    chat: number;
};

export type U32 = number;

export type U64 = number;

export type ListReviewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/reviews';
};

export type ListReviewsResponses = {
    200: Array<ReviewSummary>;
};

export type ListReviewsResponse = ListReviewsResponses[keyof ListReviewsResponses];

export type DeleteReviewData = {
    body?: never;
    path: {
        /**
         * The review's id
         */
        id: string;
    };
    query?: never;
    url: '/api/reviews/{id}';
};

export type DeleteReviewErrors = {
    404: string;
};

export type DeleteReviewError = DeleteReviewErrors[keyof DeleteReviewErrors];

export type DeleteReviewResponses = {
    204: void;
};

export type DeleteReviewResponse = DeleteReviewResponses[keyof DeleteReviewResponses];

export type ReviewStateData = {
    body?: never;
    path: {
        /**
         * The review's id
         */
        id: string;
    };
    query?: never;
    url: '/api/reviews/{id}';
};

export type ReviewStateErrors = {
    404: string;
};

export type ReviewStateError = ReviewStateErrors[keyof ReviewStateErrors];

export type ReviewStateResponses = {
    200: ReviewState;
};

export type ReviewStateResponse = ReviewStateResponses[keyof ReviewStateResponses];

export type ContextFileData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        path: string;
    };
    url: '/api/reviews/{id}/context';
};

export type ContextFileErrors = {
    400: string;
    404: string;
};

export type ContextFileError = ContextFileErrors[keyof ContextFileErrors];

export type ContextFileResponses = {
    200: FileDiff;
};

export type ContextFileResponse = ContextFileResponses[keyof ContextFileResponses];

export type RepoFilesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reviews/{id}/files';
};

export type RepoFilesErrors = {
    404: string;
};

export type RepoFilesError = RepoFilesErrors[keyof RepoFilesErrors];

export type RepoFilesResponses = {
    200: Array<string>;
};

export type RepoFilesResponse = RepoFilesResponses[keyof RepoFilesResponses];

export type RangeData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        from: string;
        /**
         * A commit; omitted for the working tree.
         */
        to?: string;
    };
    url: '/api/reviews/{id}/range';
};

export type RangeErrors = {
    400: string;
    404: string;
};

export type RangeError = RangeErrors[keyof RangeErrors];

export type RangeResponses = {
    200: Snapshot;
};

export type RangeResponse = RangeResponses[keyof RangeResponses];

export type CancelWakeData = {
    body?: never;
    path?: never;
    query: {
        waiter: string;
    };
    url: '/api/wake';
};

export type CancelWakeResponses = {
    204: void;
};

export type CancelWakeResponse = CancelWakeResponses[keyof CancelWakeResponses];

export type WakeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The agent's working directory: reviews of that repository wake it.
         */
        cwd: string;
        /**
         * The harness session, e.g. `claude:<session id>`; a newer wait replaces an older one.
         */
        waiter: string;
        timeout_secs?: number;
    };
    url: '/api/wake';
};

export type WakeResponses = {
    200: WakeNotice;
    /**
     * The wait ended with nothing to say
     */
    204: void;
};

export type WakeResponse = WakeResponses[keyof WakeResponses];
