#!/usr/bin/env python3
"""Share the demo repository (see demo-repo.py) the way an agent would, with
notes, collapsed files, test regions and a fold. Prints the review link.

    python3 scripts/demo-share.py <repo> [port]
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mcp_client import Mcp  # noqa: E402

repo = os.path.abspath(sys.argv[1])
port = sys.argv[2] if len(sys.argv) > 2 else "3433"
m = Mcp(f"http://localhost:{port}/mcp")
r = m.call("share_diff", {
  "repo_path": repo, "from": "HEAD", "title": "Add burst capacity to the limiter",
  "summary": "Limiters now allow a short **burst** on top of capacity, and `acquire` says how long to wait instead of returning false. The web badge and the log report show the new fields.",
  "annotations": [
    {"file": "src/lib.rs", "lines": [45, 54], "kind": "why", "body": "`acquire` takes `now` so tests can control time, and returns how long to wait so callers can back off instead of spinning."},
    {"file": "src/lib.rs", "lines": [60, 62], "kind": "risk", "body": "Refill now clamps to capacity + burst. A limiter that was idle refills straight to the burst ceiling."},
    {"file": "web/src/api.ts", "lines": [7, 11], "kind": "explain", "body": "A typed error so the badge can tell a 429 from a network failure."},
    {"file": "db/schema.sql", "lines": [8, 8], "kind": "question", "body": "Is an index on `reset_at` worth it? It's only used by the nightly cleanup."}
  ],
  "collapse": [{"glob": "web/src/gen/**", "reason": "generated by ts-rs"}, {"glob": "**/*.lock", "reason": "lockfile"}],
  "regions": [
    {"file": "src/lib.rs", "lines": [66, 88], "kind": "test"},
    {"file": "tests/limiter.rs", "kind": "test"},
    {"file": "web/src/api.test.ts", "kind": "test"},
    {"file": "web/src/badge.css", "lines": [7, 10], "kind": "fold", "summary": "Adds a .low style (amber) for the badge's warning state"}
  ]
})
print(r["url"])
